{
  "services": [
    {
      "type": "web",
      "name": "foodrescue-backend",
      "env": "node",
      "rootDir": "backend",
      "buildCommand": "npm install",
      "startCommand": "npm start",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "5000"
        }
      ]
    }
  ]
}
